# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\x1a\x1bgoogle/protobuf/empty.proto\"\x9d\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x10\n\x08keyInput\x18\x06 \x01(\t\x12\x12\n\nvalueInput\x18\x07 \x01(\t\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"o\n\x10ReconcileRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x10\n\x08\x66ilepath\x18\x05 \x01(\t\"$\n\x11ReconcileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"R\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"/\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tvoteGiven\x18\x02 \x01(\x08\"*\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1c\n\rWriteResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\".\n\x10HeartbeatRequest\x12\x1a\n\x12service_identifier\x18\x01 \x01(\t2\xbe\x02\n\x0bRAFTService\x12\x34\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12@\n\rReconcileLogs\x12\x16.raft.ReconcileRequest\x1a\x17.raft.ReconcileResponse\x12;\n\tHeartbeat\x12\x16.raft.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12\x30\n\x05Write\x12\x12.raft.WriteRequest\x1a\x13.raft.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPENDENTRIESREQUEST']._serialized_start=50
  _globals['_APPENDENTRIESREQUEST']._serialized_end=207
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=209
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=263
  _globals['_RECONCILEREQUEST']._serialized_start=265
  _globals['_RECONCILEREQUEST']._serialized_end=376
  _globals['_RECONCILERESPONSE']._serialized_start=378
  _globals['_RECONCILERESPONSE']._serialized_end=414
  _globals['_VOTEREQUEST']._serialized_start=416
  _globals['_VOTEREQUEST']._serialized_end=498
  _globals['_VOTERESPONSE']._serialized_start=500
  _globals['_VOTERESPONSE']._serialized_end=547
  _globals['_WRITEREQUEST']._serialized_start=549
  _globals['_WRITEREQUEST']._serialized_end=591
  _globals['_WRITERESPONSE']._serialized_start=593
  _globals['_WRITERESPONSE']._serialized_end=621
  _globals['_HEARTBEATREQUEST']._serialized_start=623
  _globals['_HEARTBEATREQUEST']._serialized_end=669
  _globals['_RAFTSERVICE']._serialized_start=672
  _globals['_RAFTSERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)
